// <auto-generated />
using System;
using AuctionApp.Core.DAL.Data.AuctionContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionApp.Core.DAL.Data.AuctionContext.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BestBidId");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuctionId");

                    b.Property<int>("AuctionRef");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(16,2)");

                    b.Property<DateTime>("DatePlaced");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Position");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMethods");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuctionRef");

                    b.Property<decimal>("ConstPrice")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int?>("DeliveryRef")
                        .IsRequired();

                    b.Property<string>("ImgSrc")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Status");

                    b.Property<int?>("SubcategoryRef")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AuctionRef")
                        .IsUnique()
                        .HasFilter("[AuctionRef] IS NOT NULL");

                    b.HasIndex("DeliveryRef");

                    b.HasIndex("SubcategoryRef");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.ItemDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<int>("ItemRef");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDescriptions");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryRef");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Position");

                    b.HasKey("Id");

                    b.HasIndex("CategoryRef");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Bid", b =>
                {
                    b.HasOne("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Item", b =>
                {
                    b.HasOne("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Auction", "Auction")
                        .WithOne("Item")
                        .HasForeignKey("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Item", "AuctionRef")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Delivery", "Delivery")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryRef");

                    b.HasOne("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Subcategory", "Subcategory")
                        .WithMany("Items")
                        .HasForeignKey("SubcategoryRef");
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.ItemDescription", b =>
                {
                    b.HasOne("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Item", "Item")
                        .WithMany("ItemDescriptions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Subcategory", b =>
                {
                    b.HasOne("AuctionApp.Core.DAL.Data.AuctionContext.Domain.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryRef")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
