// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionApp.Core.DAL.Data.AuctionContext.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(16,2)");

                    b.Property<DateTime>("DatePlaced");

                    b.Property<int?>("ItemId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Position");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.ClientBid", b =>
                {
                    b.Property<int>("BidId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.HasKey("BidId");

                    b.ToTable("ClientBids");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.ClientItem", b =>
                {
                    b.Property<int>("ItemId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.HasKey("ItemId");

                    b.ToTable("ClientItems");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activated");

                    b.Property<DateTime>("AuctionEndDate");

                    b.Property<decimal>("BuyNowPrice")
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("ImgSrc")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("SubcategoryId");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.ItemDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDescriptions");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Position");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Bid", b =>
                {
                    b.HasOne("AuctionApp.Core.AuctionContext.Domain.Item", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.ClientBid", b =>
                {
                    b.HasOne("AuctionApp.Core.AuctionContext.Domain.Bid", "Bid")
                        .WithMany("ClientBids")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.ClientItem", b =>
                {
                    b.HasOne("AuctionApp.Core.AuctionContext.Domain.Item", "Item")
                        .WithMany("ClientItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Item", b =>
                {
                    b.HasOne("AuctionApp.Core.AuctionContext.Domain.Subcategory", "Subcategory")
                        .WithMany("Items")
                        .HasForeignKey("SubcategoryId");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.ItemDescription", b =>
                {
                    b.HasOne("AuctionApp.Core.AuctionContext.Domain.Item", "Item")
                        .WithMany("Descriptions")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("AuctionApp.Core.AuctionContext.Domain.Subcategory", b =>
                {
                    b.HasOne("AuctionApp.Core.AuctionContext.Domain.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
