// <auto-generated />
using System;
using AuctionApp.Web.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuctionApp.Core.Migrations.AuctionDb
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20180613170645_ChangeClientItemAndClientBidUserIdProperty")]
    partial class ChangeClientItemAndClientBidUserIdProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuctionApp.Core.Auction.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("BidAmount");

                    b.Property<DateTime>("DatePlaced");

                    b.Property<int?>("ItemId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Position");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.ClientBid", b =>
                {
                    b.Property<int>("BidId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("BidId");

                    b.ToTable("ClientBid");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.ClientItem", b =>
                {
                    b.Property<int>("ItemId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("ItemId");

                    b.ToTable("ClientItem");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("AuctionEndDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("SubcategoryId");

                    b.HasKey("Id");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.ItemDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemDescriptions");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<short>("Position");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.Bid", b =>
                {
                    b.HasOne("AuctionApp.Core.Auction.Item", "Item")
                        .WithMany("Bids")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.ClientBid", b =>
                {
                    b.HasOne("AuctionApp.Core.Auction.Bid", "Bid")
                        .WithMany("ClientBids")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.ClientItem", b =>
                {
                    b.HasOne("AuctionApp.Core.Auction.Item", "Item")
                        .WithMany("ClientItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.Item", b =>
                {
                    b.HasOne("AuctionApp.Core.Auction.Subcategory", "Subcategory")
                        .WithMany("Items")
                        .HasForeignKey("SubcategoryId");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.ItemDescription", b =>
                {
                    b.HasOne("AuctionApp.Core.Auction.Item", "Item")
                        .WithMany("Descriptions")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("AuctionApp.Core.Auction.Subcategory", b =>
                {
                    b.HasOne("AuctionApp.Core.Auction.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
